//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class activite_compl
    {
        public activite_compl()
        {
            this.inviter = new HashSet<inviter>();
            this.realiser = new HashSet<realiser>();
        }
    
        public int id_activite_compl { get; set; }
        public Nullable<System.DateTime> date_activite { get; set; }
        public string lieu_activite { get; set; }
        public string theme_activite { get; set; }
        public string motif_activite { get; set; }
    
        public virtual ICollection<inviter> inviter { get; set; }
        public virtual ICollection<realiser> realiser { get; set; }
    }
}
