//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class fraisforfait
    {
        public fraisforfait()
        {
            this.ligne_fraisforfait = new HashSet<ligne_fraisforfait>();
        }
    
        public int id_fraisforfait { get; set; }
        public string lib_fraisforfait { get; set; }
        public Nullable<decimal> montant_frais_forfait { get; set; }
    
        public virtual ICollection<ligne_fraisforfait> ligne_fraisforfait { get; set; }
    }
}
