//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class fraishorsforfait
    {
        public int id_fraishorsforfait { get; set; }
        public int id_frais { get; set; }
        public Nullable<System.DateTime> date_fraishorsforfait { get; set; }
        public Nullable<decimal> montant_fraishorsforfait { get; set; }
        public string lib_fraishorsforfait { get; set; }
    
        public virtual frais frais { get; set; }
    }
}
