//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class frais
    {
        public frais()
        {
            this.fraishorsforfait = new HashSet<fraishorsforfait>();
            this.ligne_fraisforfait = new HashSet<ligne_fraisforfait>();
        }
    
        public int id_frais { get; set; }
        public int id_etat { get; set; }
        public string anneemois { get; set; }
        public int id_visiteur { get; set; }
        public Nullable<int> nbjustificatifs { get; set; }
        public Nullable<System.DateTime> datemodification { get; set; }
        public Nullable<decimal> montantvalide { get; set; }
    
        public virtual etat etat { get; set; }
        public virtual visiteur visiteur { get; set; }
        public virtual ICollection<fraishorsforfait> fraishorsforfait { get; set; }
        public virtual ICollection<ligne_fraisforfait> ligne_fraisforfait { get; set; }
    }
}
