//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RG_GSBE5CEntities : DbContext
    {
        public RG_GSBE5CEntities()
            : base("name=RG_GSBE5CEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activite_compl> activite_compl { get; set; }
        public DbSet<composant> composant { get; set; }
        public DbSet<constituer> constituer { get; set; }
        public DbSet<dosage> dosage { get; set; }
        public DbSet<etat> etat { get; set; }
        public DbSet<famille> famille { get; set; }
        public DbSet<formuler> formuler { get; set; }
        public DbSet<frais> frais { get; set; }
        public DbSet<fraisforfait> fraisforfait { get; set; }
        public DbSet<fraishorsforfait> fraishorsforfait { get; set; }
        public DbSet<interagir> interagir { get; set; }
        public DbSet<inviter> inviter { get; set; }
        public DbSet<laboratoire> laboratoire { get; set; }
        public DbSet<ligne_fraisforfait> ligne_fraisforfait { get; set; }
        public DbSet<medicament> medicament { get; set; }
        public DbSet<offrir> offrir { get; set; }
        public DbSet<posseder> posseder { get; set; }
        public DbSet<praticien> praticien { get; set; }
        public DbSet<prescrire> prescrire { get; set; }
        public DbSet<presentation> presentation { get; set; }
        public DbSet<rapport_visite> rapport_visite { get; set; }
        public DbSet<realiser> realiser { get; set; }
        public DbSet<region> region { get; set; }
        public DbSet<secteur> secteur { get; set; }
        public DbSet<specialite> specialite { get; set; }
        public DbSet<stats_prescriptions> stats_prescriptions { get; set; }
        public DbSet<travailler> travailler { get; set; }
        public DbSet<type_individu> type_individu { get; set; }
        public DbSet<type_praticien> type_praticien { get; set; }
        public DbSet<visiteur> visiteur { get; set; }
    }
}
