//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class posseder
    {
        public int id_praticien { get; set; }
        public int id_specialite { get; set; }
        public string diplome { get; set; }
        public Nullable<decimal> coef_prescription { get; set; }
    
        public virtual praticien praticien { get; set; }
        public virtual specialite specialite { get; set; }
    }
}
