//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class rapport_visite
    {
        public rapport_visite()
        {
            this.offrir = new HashSet<offrir>();
        }
    
        public int id_rapport { get; set; }
        public Nullable<int> id_praticien { get; set; }
        public int id_visiteur { get; set; }
        public Nullable<System.DateTime> date_rapport { get; set; }
        public string bilan { get; set; }
        public string motif { get; set; }
    
        public virtual ICollection<offrir> offrir { get; set; }
        public virtual praticien praticien { get; set; }
        public virtual visiteur visiteur { get; set; }
    }
}
