//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public region()
        {
            this.travailler = new HashSet<travailler>();
        }
    
        public int id_region { get; set; }
        public Nullable<int> id_secteur { get; set; }
        public string nom_region { get; set; }
    
        public virtual secteur secteur { get; set; }
        public virtual ICollection<travailler> travailler { get; set; }
    }
}
