//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur
    {
        public secteur()
        {
            this.region = new HashSet<region>();
            this.visiteur = new HashSet<visiteur>();
        }
    
        public int id_secteur { get; set; }
        public string lib_secteur { get; set; }
    
        public virtual ICollection<region> region { get; set; }
        public virtual ICollection<visiteur> visiteur { get; set; }
    }
}
