//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialite
    {
        public specialite()
        {
            this.posseder = new HashSet<posseder>();
        }
    
        public int id_specialite { get; set; }
        public string lib_specialite { get; set; }
    
        public virtual ICollection<posseder> posseder { get; set; }
    }
}
