//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats_prescriptions
    {
        public int id_praticien { get; set; }
        public int id_medicament { get; set; }
        public int annee_mois { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual medicament medicament { get; set; }
        public virtual praticien praticien { get; set; }
    }
}
