//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_praticien
    {
        public type_praticien()
        {
            this.praticien = new HashSet<praticien>();
        }
    
        public int id_type_praticien { get; set; }
        public string lib_type_praticien { get; set; }
        public string lieu_type_praticien { get; set; }
    
        public virtual ICollection<praticien> praticien { get; set; }
    }
}
